// Presentation vocabulary only: metadata identities, discovery and tree schemas belong to eska.
const labels: Readonly<Record<string, readonly [string, string]>> = {
  "configuration": ["Конфигурация", "Configuration"],
  "data-processor": ["Обработка", "Data processor"],
  "report": ["Отчёт", "Report"],
  "accounting-register": ["Регистр бухгалтерии", "Accounting register"],
  "accumulation-register": ["Регистр накопления", "Accumulation register"],
  "bot": ["Бот", "Bot"],
  "business-process": ["Бизнес-процесс", "Business process"],
  "calculation-register": ["Регистр расчёта", "Calculation register"],
  "catalog": ["Справочник", "Catalog"],
  "chart-of-accounts": ["План счетов", "Chart of accounts"],
  "chart-of-calculation-types": ["План видов расчёта", "Chart of calculation types"],
  "chart-of-characteristic-types": ["План видов характеристик", "Chart of characteristic types"],
  "command-group": ["Группа команд", "Command group"],
  "common-attribute": ["Общий реквизит", "Common attribute"],
  "common-command": ["Общая команда", "Common command"],
  "common-form": ["Общая форма", "Common form"],
  "common-module": ["Общий модуль", "Common module"],
  "common-picture": ["Общая картинка", "Common picture"],
  "common-template": ["Общий макет", "Common template"],
  "constant": ["Константа", "Constant"],
  "defined-type": ["Определяемый тип", "Defined type"],
  "document": ["Документ", "Document"],
  "document-journal": ["Журнал документов", "Document journal"],
  "document-numerator": ["Нумератор", "Document numerator"],
  "enum": ["Перечисление", "Enumeration"],
  "event-subscription": ["Подписка на событие", "Event subscription"],
  "exchange-plan": ["План обмена", "Exchange plan"],
  "external-data-source": ["Внешний источник данных", "External data source"],
  "filter-criterion": ["Критерий отбора", "Filter criterion"],
  "functional-option": ["Функциональная опция", "Functional option"],
  "functional-option-parameter": ["Параметр функциональных опций", "Functional options parameter"],
  "http-service": ["HTTP-сервис", "HTTP service"],
  "information-register": ["Регистр сведений", "Information register"],
  "integration-service": ["Сервис интеграции", "Integration service"],
  "language": ["Язык", "Language"],
  "role": ["Роль", "Role"],
  "scheduled-job": ["Регламентное задание", "Scheduled job"],
  "sequence": ["Последовательность", "Sequence"],
  "session-parameter": ["Параметр сеанса", "Session parameter"],
  "settings-storage": ["Хранилище настроек", "Settings storage"],
  "style": ["Стиль", "Style"],
  "style-item": ["Элемент стиля", "Style item"],
  "subsystem": ["Подсистема", "Subsystem"],
  "task": ["Задача", "Task"],
  "web-service": ["Web-сервис", "Web service"],
  "web-socket-client": ["WebSocket-клиент", "WebSocket client"],
  "ws-reference": ["WS-ссылка", "WS reference"],
  "xdto-package": ["XDTO-пакет", "XDTO package"],
  "form": ["Форма", "Form"],
  "template": ["Макет", "Template"],
  "command": ["Команда", "Command"],
  "addressing-attribute": ["Реквизит адресации", "Addressing attribute"],
  "attribute": ["Реквизит", "Attribute"],
  "tabular-section": ["Табличная часть", "Tabular section"],
  "dimension": ["Измерение", "Dimension"],
  "resource": ["Ресурс", "Resource"],
  "requisite": ["Реквизит", "Requisite"],
  "enum-value": ["Значение перечисления", "Enumeration value"],
  "accounting-flag": ["Признак учёта", "Accounting flag"],
  "ext-dimension-accounting-flag": ["Признак учёта субконто", "Subconto accounting flag"],
  "predefined-item": ["Предопределённый элемент", "Predefined item"],
  "recalculation": ["Перерасчёт", "Recalculation"],
  "column": ["Колонка", "Column"],
  "url-template": ["Шаблон URL", "URL template"],
  "method": ["Метод", "Method"],
  "operation": ["Операция", "Operation"],
  "parameter": ["Параметр", "Parameter"],
  "integration-service-channel": ["Канал сервиса интеграции", "Integration service channel"],
};

/** Translate known protocol kinds; keep future backend kinds visible without guessing their meaning. */
export function kindLabel(kind: string, language: "ru-RU" | "en-US"): string {
  return Object.hasOwn(labels, kind) ? labels[kind]?.[language === "ru-RU" ? 0 : 1] ?? kind : kind;
}
